#! /bin/bash
size=${1:-128}
SAUER_RESOURCE_DIR=/Applications/Sauerbraten.app/Contents/Resources/

while IFS= read -r line
do
	[[ "$line" =~ ^(//.*$|$) ]] && continue
	dst=${line%: *}
	src=${SAUER_RESOURCE_DIR}/packages/textures/${line#*: }
	echo "$dst"
	convert "$src" -scale "$size" "$dst"
done < <(sed 's/^ *//g' locations.txt)
